spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AZ
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect